#!/usr/bin/env bash
# redirects /redirect_me to another page
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
file="/etc/nginx/sites-available/default"
sudo chmod +w $file
# Add redirection location block
cmd1="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
sudo sed -i "/server_name _;/a $cmd1" $file
sudo service nginx restart
