#!/usr/bin/env bash
# custom 404 page
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
file="/etc/nginx/sites-available/default"
sudo chmod +w $file
# Add redirection location block
cmd1="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
sudo sed -i "/server_name _;/a $cmd1" $file

# Add custom 404 page configuration block after a specific marker
marker="# Custom 404 Page Configuration"
cmd2="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}\n"
sudo sed -i "/listen 80 default_server;/a $cmd2" $file
sudo service nginx restart
